### PR TITLE
(Fix) / add spinner

### LINKED ISSUE #615: Add spinner
There seems not to be any indicator / spinner working when using the categories / filters / search / etc.

Check if it's working, and fix if necessary.

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #615

There should be a spinner when changing categories / filters / etc. (nothing was shown before).

### CODE REVIEW

File: app/src/components/market/sections/market_list/market_home_container.tsx [hunk 1]
```diff
@@ -106,32 +107,43 @@ const MarketHomeContainer: React.FC = () => {
...
+      setIsFiltering(false)
+    } else if (error) {
+      setMarkets(RemoteData.failure(error))
+      setIsFiltering(false)
     }
-  }, [fetchedMarkets, loading, error, context.networkId])
+  }, [fetchedMarkets, loading, error, context.networkId, markets])
 
   const onFilterChange = useCallback((filter: any) => {
-    setMoreMarkets(true)
```
Comment (fvictorio) [inline app/src/components/market/sections/market_list/market_home_container.tsx:122]: Why is this removed?

File: app/src/components/market/sections/market_list/market_home_container.tsx [hunk 2]
```diff
@@ -106,32 +107,43 @@ const MarketHomeContainer: React.FC = () => {
...
     setFilter(filter)
+    setIsFiltering(true)
```
Comment (fvictorio) [inline app/src/components/market/sections/market_list/market_home_container.tsx:128]: I wonder if, instead of adding this flag, we could set markets to `RemoteData.loading()` here. Anyway, not a blocker, but it seems like `isFiltering` is kind of redundant.

File: app/src/components/market/sections/market_list/market_home_container.tsx (hunk 1 above)
Comment (gabitoesmiapodo) [reply app/src/components/market/sections/market_list/market_home_container.tsx:122]: It was showing the button when it was not needed IIRC.

Generally speaking, my intention was to not to display the button unless there are more than 10 items. The way it was implemented before it was always displayed, and hidden when trying to load more elements and finding there were not more than 10, or no more items to load.

File: app/src/components/market/sections/market_list/market_home_container.tsx (hunk 2 above)
Comment (gabitoesmiapodo) [reply app/src/components/market/sections/market_list/market_home_container.tsx:128]: Well, I didn't know we could do that.

Tried to make the UI display a spinner every time there was an ongoing `RemoteData.loading()` but it seemed to trigger only when loading data / more data, not when filtering it.
