### PR TITLE
Fix some feedback for milestone 5

### LINKED ISSUE #277: The initial probabilities for an outcome cannot be zero

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #277 

### Includes
- Improve messages when a user redeems and resolve condition
- Add validation in the step 2 in the market wizard creation for probabilities

### CODE REVIEW

File: app/src/components/market/market_home.tsx [hunk 1]
```diff
@@ -62,7 +62,7 @@ export const MarketHome: React.FC<Props> = (props: Props) => {
         {RemoteData.hasData(markets) &&
           markets.data.length > 0 &&
           markets.data.slice(0, count).map(item => {
-            return <ListItem key={item.conditionId} data={item}></ListItem>
+            return <ListItem key={`${item.address}_${item.conditionId}`} data={item}></ListItem>
```
Comment (fvictorio) [inline app/src/components/market/market_home.tsx]: This should be fine but I'm curious, how did you get two outcomes with the same `conditionId` (assuming that's why you did this).

File: app/src/components/market/profile/closed_market_detail.tsx [hunk 2]
```diff
@@ -109,13 +119,14 @@ export const ClosedMarketDetailWrapper = (props: Props) => {
...
       if (!isConditionResolved) {
         setMessage('Resolving condition...')
-        await resolveCondition()
+        // Balances length is the number of outcomes
+        await oracle.resolveCondition(questionId, balances.length)
       }
-      setMessage('Redeem payout...')
-      setStatus(Status.Loading)
 
+      setMessage('Redeem payout...')
```
Comment (fvictorio) [inline app/src/components/market/profile/closed_market_detail.tsx]: Should we also add a `setMessage('Resolving condition...')` line before the if? Or maybe just move this line before the if?

File: app/src/components/market/market_home.tsx (hunk 1 above)
Comment (mariano-aguero) [reply app/src/components/market/market_home.tsx]: Mmmm this is happening with rinkeby, you can check the screenshot, Why is this happening ? I think we need to investigate more deeply...

Screenshot_20191219_103141

File: app/src/components/market/profile/closed_market_detail.tsx (hunk 2 above)
Comment (mariano-aguero) [reply app/src/components/market/profile/closed_market_detail.tsx]: I think the message should be added inside the `if` , is only needed when the condition is not resolved. Mmmm you make me think why we need to put this message before the `if` , do you have any concern about ? Please let me know, your thoughts are really appreciated. This is how it looks now...

Screenshot_20191219_103405

I tested and works pretty good

File: app/src/components/market/market_home.tsx (hunk 1 above)
Comment (fvictorio) [reply app/src/components/market/market_home.tsx]: Weird. Well, it's OK then.

File: app/src/components/market/profile/closed_market_detail.tsx (hunk 2 above)
Comment (fvictorio) [reply app/src/components/market/profile/closed_market_detail.tsx]: Yeah, inside the `if` is better. And it's just because the user will get 2 transactions, and so I think it's better to explain what each one is doing.
