### PR TITLE
The app crashes when an unsupported network is used

### LINKED ISSUE #392: App doesn't work when metamask is not installed
The app should be usable when the user doesn't have metamask installed. They should be able to use everything that is available without connection. When the wallet connection modal is shown, the metamask option should be disabled.

### LINKED ISSUE #393: The app crashes when an unsupported network is used
If the user is connected to, for example, Görli, the app just crashes. We should show a message like "Please connect to Mainnet or to one of the supported testnets (Rinkeby, Kovan)"

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #392 
Closes #393 

#### Includes
- Check if a web3 (legacy) or ethereum object is inyected in the browser (Metamask installed ? )
- Remove metamask item in the modal connection if metamask is not installed
- Validate wrong network selection in the wallet

### CODE REVIEW

File: app/src/components/common/modal_connect_wallet/index.tsx [hunk 1]
```diff
@@ -155,12 +157,14 @@ export const ModalConnectWallet = (props: Props) => {
...
 
+  const doesMetamaskExist = 'ethereum' in window || 'web3' in window
+
   return (
     <>
       {!context.account && (
         <ModalWrapper isOpen={isOpen} onRequestClose={onClickCloseButton} title={`Choose a Wallet`}>
-          <ItemMetamask />
-          <ItemWallet />
+          {doesMetamaskExist && <ItemMetamask />}
```
Comment (fvictorio) [inline app/src/components/common/modal_connect_wallet/index.tsx]: I think it's better to disable it rather than hiding it. @leolower @gabitoesmiapodo wdyt?

File: app/src/components/common/wrong_network_message/index.tsx [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+}
+
+const WrongNetworkMessageContainer = (props: Props) => {
+  return (
+    <>
+      <SectionTitle title="THERE WAS A PROBLEM..." />
+      <ViewCard>
+        <SubsectionTitle>Wrong network configuration</SubsectionTitle>
+        <WrappedText>
+          We couldn&apos;t find the network with the provided wallet configuration.
```
Comment (fvictorio) [inline app/src/components/common/wrong_network_message/index.tsx]: I'm pretty sure (but not 100% sure) that you can use `'` in JSX.

File: app/src/components/common/wrong_network_message/index.tsx [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+        </WrappedText>
+        <WrappedText>
+          The valid networks to use are{' '}
+          <strong>
+            {Object.keys(networkIds)
+              .join(', ')
+              .toLowerCase()}
```
Comment (fvictorio) [inline app/src/components/common/wrong_network_message/index.tsx]: Let's show the labels instead of the network ids. Let's also filter ganache out since most users won't care.

File: app/src/components/common/wrong_network_message/index.tsx [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+          </strong>
+          .
+        </WrappedText>
+        <WrappedText>
+          Please check the network configuration in your wallet and come back again.
+        </WrappedText>
+        <ButtonContainer>
+          <ButtonLinkStyled onClick={() => window.location.reload(false)}>
+            Reload with Infura
```
Comment (fvictorio) [inline app/src/components/common/wrong_network_message/index.tsx]: Not sure about this. It seems to me like exposing an implementation detail to the user. Just `Reload` would be fine.

File: app/src/components/common/modal_connect_wallet/index.tsx (hunk 1 above)
Comment (gabitoesmiapodo) [reply app/src/components/common/modal_connect_wallet/index.tsx]: Yes.

Comment (mariano-aguero) [reply app/src/components/common/modal_connect_wallet/index.tsx]: I will need to add some opacity, like in this image, because this component is a Div
Screenshot_20200204_181840

Comment (gabitoesmiapodo) [reply app/src/components/common/modal_connect_wallet/index.tsx]: That's fine.

Comment (mariano-aguero) [reply app/src/components/common/modal_connect_wallet/index.tsx]: Done!

File: app/src/components/common/wrong_network_message/index.tsx (hunk 2 above)
Comment (mariano-aguero) [reply app/src/components/common/wrong_network_message/index.tsx]: We will incur in this linter error 
Screenshot_20200204_183837

File: app/src/components/common/wrong_network_message/index.tsx (hunk 3 above)
Comment (mariano-aguero) [reply app/src/components/common/wrong_network_message/index.tsx]: The keys are the labels, I will filter ganache.

File: app/src/components/common/wrong_network_message/index.tsx (hunk 4 above)
Comment (mariano-aguero) [reply app/src/components/common/wrong_network_message/index.tsx]: Rewording

File: app/src/components/common/wrong_network_message/index.tsx (hunk 3 above)
Comment (mariano-aguero) [reply app/src/components/common/wrong_network_message/index.tsx]: Screenshot_20200204_185433
